platform :ios, ‘8.0’

target ‘TGJKSH’ do
  pod 'AFNetworking', '~> 3.1.0'
  pod 'TMCache', '~> 2.1.0'
  pod 'Reachability', '~> 3.2'
  pod 'SDWebImage', '~>3.7'
  pod 'MJRefresh', '~> 3.1.10'
  pod 'Masonry', '~> 1.0.1'
  pod 'MJExtension', '~> 3.0.12'
  pod 'SVProgressHUD', '~> 2.0.3'

    pod 'HMSegmentedControl', '~> 1.5.2'
    pod 'SDCycleScrollView', '~> 1.65'
end